### ISSUE TITLE
Is it still needed to maintain keybindings.lua

### ISSUE THREAD

**Issue by eshepelyuk** [kcl-lang/vim-kcl#13]
Hello @Peefy @He1pa 

The file `lua/keybindings.lua` contains bindings for comment/uncomment lines, 
but such sort of functionality is better handled by existing plugins like https://github.com/numToStr/Comment.nvim 
or any other.
Since plugin is properly setting `commentstring` - then any _comment related_ plugin will properly pick them up.

Does it still make sense maintain those bindings ? Or maybe this can be dropped as well ?

**Comment by Peefy** [comment]
cc @He1pa

**Comment by He1pa** [comment]
I don't think it's a good idea to delete these keybindings directly. After deleting them, if users need to use the comment, they need to install other plugins. This may also be a little burden.
Considering those who don't installed other plugins(or even don't know about these), perhaps a way to make these bindings compatible with other plugins is needed instead of deleting them directly.

**Comment by eshepelyuk** [comment]
> After deleting them, if users need to use the comment, they need to install other plugins.

Exactly, this is Vim/NeoVIm ideology - one plugin for one thing. 
Language plugins in NeoVIm are not brining any keybindings - they setup syntax highlight, filetype detection, commenstring etc.
Neovim has standard comment keybinding `gc` and there's no need to invent new ones.

```
:help gc
```

**Comment by Peefy** [comment]
I think we can investigate the practices of mainstream language plugins. This file `keybindings.lua` was initially contributed by other members of the community and may not necessarily be a standard practice. cc @He1pa
